### PR TITLE
causal and non-causal paths

### PR DESCRIPTION
**Pull request by jhcreed**

### CODE REVIEW

**Review by gadenbuie — DISMISSED** [review]
It looks like both `openExpOutcomePaths` and `openExpOutcomePathsIndirect` will output the same help/error messages twice. Rather than duplicating the error message, I think it'd be less confusing to output a single message when there's help text or an error.

Since all calculations (including error messages) are derived from the same object, they could instead be in a single `renderUI()`.

**Comment by gadenbuie** [comment]
@jhcreed can you please describe a simple example that demos the expected behavior of the features added in this branch?

**Comment by jhcreed** [comment]
Previously after specifying the exposure and outcome (and adjustment variables if any existed) all the open paths would be displayed, but now the open paths are separated into causal and non-causal paths. An additional text box has been added to show the minimal adjustment set - variables that need to be adjusted for to close open paths.

**Comment by jhcreed** [comment]
Ok so loading the mediator with confounding example with E being exposure and Y being the outcome. You use to get the message  E -> M -> Y and E <- C -> Y under open paths, but now E -> M -> Y appears under "Open causal associations" and E <- C -> Y appears under "Open non-causal associations" and the new minimal adjustment set returns C. If you adjust for C then the "Open non-causal associations" box is empty. If there is no minimal adjustment set, open causal paths or open non-causal paths then nothing should be returned.

**Pull request merged**
